// ===== GAMEMODES (20 tiers) =====
// icon = Minecraft-style emoji / symbol
const GAMEMODES = [
  { id: "beast", name: "Beast", icon: "🦁", short: "Beast" },
  { id: "dpot", name: "Dpot", icon: "💎", short: "Dpot" },
  { id: "npot", name: "Npot", icon: "🧪", short: "Npot" },
  { id: "dsmp", name: "Dsmp", icon: "🛡️", short: "Dsmp" },
  { id: "nsmp", name: "Nsmp", icon: "🖤", short: "Nsmp" },
  { id: "uhc", name: "UHC", icon: "❤️", short: "UHC" },
  { id: "axe", name: "Axe", icon: "🪓", short: "Axe" },
  { id: "crystal", name: "Crystal", icon: "🔮", short: "Cry" },
  { id: "cart", name: "Cart", icon: "🛒", short: "Cart" },
  { id: "mace", name: "Mace", icon: "🔨", short: "Mace" },
  { id: "op", name: "OP", icon: "⚡", short: "OP" },
  { id: "creeper", name: "Creeper", icon: "💥", short: "Crpr" },
  { id: "spearmace", name: "Spear Mace", icon: "🗡️", short: "SMace" },
  { id: "spearelytra", name: "Spear Elytra", icon: "🪽", short: "SEly" },
  { id: "rodmace", name: "Rod Mace", icon: "🎣", short: "RMace" },
  { id: "trident", name: "Trident", icon: "🔱", short: "Tri" },
  { id: "shieldsuhc", name: "Shields UHC", icon: "🛡️", short: "ShUHC" },
  { id: "elytramace", name: "Elytra Mace", icon: "🪽", short: "EMace" },
  { id: "lifesteal", name: "Lifesteal", icon: "💉", short: "LS" },
  { id: "spearsmp", name: "Spear SMP", icon: "⚔️", short: "SSMP" },
];

// Tier order for points calculation (higher = better)
const TIER_POINTS = {
  HT1: 60,
  LT1: 45,
  HT2: 30,
  LT2: 20,
  HT3: 10,
  LT3: 6,
  HT4: 4,
  LT4: 3,
  HT5: 2,
  LT5: 1,
};

const TIER_ORDER = [
  "HT1",
  "LT1",
  "HT2",
  "LT2",
  "HT3",
  "LT3",
  "HT4",
  "LT4",
  "HT5",
  "LT5",
];

// ===== PLAYERS DATA =====
// To add a new player — copy an object and fill the fields.
// tiers: { gamemodeId: "HT1" | "LT2" | ... }
const PLAYERS = [
  {
    name: "Cr1m3",
    region: "UK",
    uuid: "f6a1e0c0-8b3a-4f2e-9c1d-7e5a6b8c9d0e", // optional, for skin
    tiers: {
      beast: "HT1",
      dpot: "HT1",
      npot: "HT1",
      dsmp: "HT1",
      nsmp: "LT1",
      uhc: "HT1",
      axe: "HT1",
      crystal: "LT1",
      cart: "HT1",
      mace: "LT1",
      op: "LT1",
      creeper: "",
      spearmace: "",
      spearelytra: "",
      rodmace: "",
      trident: "",
      shieldsuhc: "",
      elytramace: "",
      lifesteal: "",
      spearsmp: "",
    },
  },
  {
    name: "Comonyat",
    region: "UK",
    uuid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    tiers: {
      beast: "HT1",
      dpot: "LT1",
      npot: "HT2",
      dsmp: "LT1",
      nsmp: "LT1",
      uhc: "LT1",
      axe: "LT1",
      crystal: "HT1",
      cart: "LT1",
      mace: "HT1",
      op: "HT2",
      creeper: "",
      spearmace: "",
      spearelytra: "",
      rodmace: "",
      trident: "",
      shieldsuhc: "",
      elytramace: "",
      lifesteal: "",
      spearsmp: "",
    },
  },
  {
    name: "SuperiorRasul",
    region: "KZ",
    tiers: {
      beast: "LT1",
      dpot: "LT1",
      npot: "HT1",
      dsmp: "LT1",
      nsmp: "HT1",
      uhc: "LT1",
      axe: "LT1",
      crystal: "LT2",
      cart: "HT2",
      mace: "LT1",
      op: "HT1",
      creeper: "",
      spearmace: "",
      spearelytra: "",
      rodmace: "",
      trident: "",
      shieldsuhc: "",
      elytramace: "",
      lifesteal: "",
      spearsmp: "",
    },
  },
];
